language: node_js
node_js:
  - "stable"

script:
  - npm run lint
  - npm run build
  - npm test

deploy:
  provider: npm
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_AUTH_TOKEN"
  on:
    tags: true
